# Generated by Django 5.2.6 on 2025-12-20 06:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_subscriber_tag_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.CharField(help_text="e.g., 'Dec 2024' or '2024'", max_length=50)),
                ('expiry_date', models.CharField(blank=True, max_length=50)),
                ('credential_id', models.CharField(blank=True, max_length=200)),
                ('credential_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('icon', models.CharField(blank=True, help_text="FontAwesome icon class, e.g., 'fas fa-star'", max_length=100)),
                ('content', models.TextField(blank=True, help_text='Rich text content (supports HTML)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_nav', models.BooleanField(default=True, help_text='Show this section in navigation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Section',
                'verbose_name_plural': 'Custom Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(help_text="e.g. 'Depuis 2025' or '2021–2025'", max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(help_text='Institution name', max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('company_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.CharField(help_text="e.g., 'Jan 2023' or '2023'", max_length=50)),
                ('end_date', models.CharField(blank=True, help_text='Leave blank for current position', max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['order', '-is_current'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text="FontAwesome icon class, e.g., 'fas fa-music'", max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(choices=[('native', 'Native / Bilingual'), ('fluent', 'Fluent'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Djousse Tedongmene Alex', max_length=100)),
                ('hero_title', models.CharField(default='Futur Actuaire & Data Scientist', help_text='Main headline displayed in the hero section', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, help_text='Optional subtitle below the main headline', max_length=300)),
                ('email', models.EmailField(default='alextedongmene@gmail.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(default='7011 Ghlin, Belgique', max_length=100)),
                ('profile_image', models.ImageField(blank=True, help_text='Main profile/avatar image', null=True, upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('hero_background', models.ImageField(blank=True, help_text='Background image for hero section', null=True, upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('bio', models.TextField(default='Étudiant en Master Sciences Actuarielles (ULB)...', help_text='Main bio/about text')),
                ('bio_short', models.CharField(blank=True, help_text='Short bio for previews and meta descriptions', max_length=300)),
                ('resume', models.FileField(blank=True, help_text='Upload your resume/CV file', null=True, upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('github_url', models.URLField(blank=True, default='https://github.com/aldjoted')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title for the website', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for the website', max_length=160)),
                ('show_blog', models.BooleanField(default=True, help_text='Show blog section')),
                ('show_projects', models.BooleanField(default=True, help_text='Show projects section')),
                ('show_contact', models.BooleanField(default=True, help_text='Show contact form')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('dribbble', 'Dribbble'), ('behance', 'Behance'), ('medium', 'Medium'), ('dev', 'Dev.to'), ('stackoverflow', 'Stack Overflow'), ('codepen', 'CodePen'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('website', 'Website'), ('other', 'Other')], default='website', max_length=50)),
                ('custom_icon_class', models.CharField(blank=True, help_text="Custom FontAwesome class, e.g., 'fab fa-spotify'", max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.customsection')),
            ],
            options={
                'verbose_name': 'Custom Section Item',
                'verbose_name_plural': 'Custom Section Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='api.experience')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='api.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.skillgroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
