# Generated by Django 5.2.6 on 2025-12-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_certification_customsection_education_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgroup',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-code', help_text="FontAwesome icon class, e.g., 'fas fa-code'", max_length=100),
        ),
        migrations.AddField(
            model_name='skillitem',
            name='proficiency',
            field=models.IntegerField(default=0, help_text='Proficiency level from 0 to 100'),
        ),
    ]
